name: 🪂 Continuous Deployment

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  release:
    types: [published, edited, prereleased]

jobs:
  build:
    name: 🔨 Build and deploy to ghcr
    uses: clamsproject/.github/.github/workflows/app-container.yml@main
