name: 🪂 Continuous Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published, edited, prereleased]

jobs:
  build:
    name: 🔨 Build and deploy to ghcr
    uses: clamsproject/.github/.github/workflows/app-docker-ghcr.yml@main
